# 损失函数

### 激活函数

relu: tf.nn.relu()  
sigmoid: tf.nn.sigmoid()  
tanh: tf.nn.tanh()

#### mse: tf.reduce_mean(tf.suqare(y-y_))

In [2]:
import tensorflow as tf 
import numpy as np

In [3]:
BATCH_SIZE=8
SEED=23455

In [4]:
rdm=np.random.RandomState(SEED)
X= rdm.rand(32,2)
Y_=[[x1+x2+(rdm.rand()/10.0-0.05)] for (x1,x2) in X]

In [6]:
x=tf.placeholder(tf.float32,shape=(None,2))
y_=tf.placeholder(tf.float32,shape=(None,1))
w1=tf.Variable(tf.random_normal([2,1],stddev=1,seed=1))
y=tf.matmul(x,w1)

Instructions for updating:
Colocations handled automatically by placer.


In [7]:
lose_mse=tf.reduce_mean(tf.square(y-y_))
train_step=tf.train.GradientDescentOptimizer(0.001).minimize(lose_mse)

In [14]:
with tf.Session() as sess:
    init_op=tf.global_variables_initializer()
    sess.run(init_op)
    STEPS=20000
    for i in range(STEPS):
        start=(i*BATCH_SIZE)%32
        end=start+BATCH_SIZE
        sess.run(train_step,feed_dict={x:X[start:end],y_:Y_[start:end]})
        if i %500==0:
            total_loss= sess.run(lose_mse,feed_dict={x:X,y_:Y_})
            print("After %d training step(s), loss on all data is %g"%(i,total_loss))
            print("w1 is:\n",sess.run(w1))
    print("Final w1 is :\n",sess.run(w1))

After 0 training step(s), loss on all data is 0.655701
w1 is:
 [[-0.80974597]
 [ 1.4852903 ]]
After 500 training step(s), loss on all data is 0.35731
w1 is:
 [[-0.46074435]
 [ 1.641878  ]]
After 1000 training step(s), loss on all data is 0.232481
w1 is:
 [[-0.21939856]
 [ 1.6984766 ]]
After 1500 training step(s), loss on all data is 0.170404
w1 is:
 [[-0.04415595]
 [ 1.7003176 ]]
After 2000 training step(s), loss on all data is 0.133037
w1 is:
 [[0.08942621]
 [1.673328  ]]
After 2500 training step(s), loss on all data is 0.106939
w1 is:
 [[0.19583555]
 [1.6322677 ]]
After 3000 training step(s), loss on all data is 0.0870619
w1 is:
 [[0.28375748]
 [1.5854434 ]]
After 3500 training step(s), loss on all data is 0.0712709
w1 is:
 [[0.35848638]
 [1.5374472 ]]
After 4000 training step(s), loss on all data is 0.0584907
w1 is:
 [[0.42332518]
 [1.4907393 ]]
After 4500 training step(s), loss on all data is 0.0480653
w1 is:
 [[0.48040026]
 [1.4465574 ]]
After 5000 training step(s), loss on all da

### 自定义损失函数

例子： 预测销量，预测多了损失的是成本，少了，损失的是利润

In [27]:
BATCH_SIZE=8
SEED=23455
COST= 9
PROFIT=1

In [28]:
rdm=np.random.RandomState(SEED)
X= rdm.rand(32,2)
Y_=[[x1+x2+(rdm.rand()/10.0-0.05)] for (x1,x2) in X]

In [29]:
x=tf.placeholder(tf.float32,shape=(None,2))
y_=tf.placeholder(tf.float32,shape=(None,1))
w1=tf.Variable(tf.random_normal([2,1],stddev=1,seed=1))
y=tf.matmul(x,w1)

#### 损失函数改变

In [30]:
loss=tf.reduce_sum(tf.where(tf.greater(y,y_),(y-y_)*COST,(y_-y)*PROFIT))
train_step=tf.train.GradientDescentOptimizer(0.001).minimize(loss)

In [31]:
with tf.Session() as sess:
    init_op=tf.global_variables_initializer()
    sess.run(init_op)
    STEPS=20000
    for i in range(STEPS):
        start=(i*BATCH_SIZE)%32
        end=start+BATCH_SIZE
        sess.run(train_step,feed_dict={x:X[start:end],y_:Y_[start:end]})
        if i %500==0:
            total_loss= sess.run(loss,feed_dict={x:X,y_:Y_})
            print("After %d training step(s), loss on all data is %g"%(i,total_loss))
            print("w1 is:\n",sess.run(w1))
    print("Final w1 is :\n",sess.run(w1))

After 0 training step(s), loss on all data is 29.8745
w1 is:
 [[-0.80594873]
 [ 1.4873729 ]]
After 500 training step(s), loss on all data is 2.38814
w1 is:
 [[0.8732146]
 [1.006204 ]]
After 1000 training step(s), loss on all data is 1.46394
w1 is:
 [[0.9658064]
 [0.9698208]]
After 1500 training step(s), loss on all data is 1.46911
w1 is:
 [[0.9645447]
 [0.9682946]]
After 2000 training step(s), loss on all data is 1.43915
w1 is:
 [[0.9602475]
 [0.9742084]]
After 2500 training step(s), loss on all data is 1.45907
w1 is:
 [[0.96100295]
 [0.96993417]]
After 3000 training step(s), loss on all data is 1.43333
w1 is:
 [[0.9654102]
 [0.9761159]]
After 3500 training step(s), loss on all data is 1.43359
w1 is:
 [[0.96414846]
 [0.9745897 ]]
After 4000 training step(s), loss on all data is 1.44526
w1 is:
 [[0.95985126]
 [0.9805035 ]]
After 4500 training step(s), loss on all data is 1.46411
w1 is:
 [[0.9636422]
 [0.9687893]]
After 5000 training step(s), loss on all data is 1.44187
w1 is:
 [[0.95934

### 交叉熵

cross_entropy: -tf.reduce_mean(y_*tf.log(tf.clip_by_value(y,1e-12,1.0)))  
tf.clip_by_value() y小于1e-12为1e-12 ，大于1 为1

1e-12 防止出现log0

#### 实际用以下函数

引入 softmax() 

ce = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=y,lables=tf.argmax(y_,1))  
cem= tf.reduce_mean(ce)